<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>CS_Navigation</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <PublishTrimmed>true</PublishTrimmed> <!-- Hapus IL yang ga kepake -->
    <PublishAot>true</PublishAot>         <!-- AOT Compilation -->
    <InvariantGlobalization>true</InvariantGlobalization> <!-- Lebih kecil -->
    <StripSymbols>true</StripSymbols>     <!-- Hilangkan simbol debug -->
    <TrimMode>link</TrimMode>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SelfContained>true</SelfContained>    
  </PropertyGroup>

  <!-- WINDOWS -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <!-- AOT dan SingleFile gak bisa bareng -->
    <PublishSingleFile>false</PublishSingleFile>

    <OutputPath>Bin/Build/</OutputPath>             <!-- Output build -->
    <PublishDir>Bin/Publish/</PublishDir>           <!-- Output publish -->

    <!-- Optimization -->
    <Optimize>true</Optimize>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- Trimming & Size Optimization -->
    <PublishTrimmed>true</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>

    <!-- AOT Native Compilation -->
    <PublishAot>true</PublishAot>
    <IlcDisableReflection>true</IlcDisableReflection>
    <IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>

    <!-- Compression -->
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  
</Project>
